"""Generate a minimal 1-task spec bundle for non-``spec_driven`` runs.

When the Triage agent classifies an issue as ``bug_fix`` / ``upgrade`` /
``docs``, the dispatcher renders a tiny three-document spec bundle from
the issue context and uploads it to ``s3://{artifacts}/specs/{slug}/``.
The SDLC state machine's synthetic-spec branch picks up that prefix and
hands it straight to the Implementer — no Architect, no Critic, no spec
gate.

The format mirrors what ``architect.spec.render_*`` produces, just with
a single task. The Implementer's ``tasks.py`` parser is permissive about
extra prose, so future richer kinds (e.g., a 2-task ``upgrade`` flow:
scan + bump) can extend this without touching the parser.
"""

from __future__ import annotations

from typing import Literal

WorkflowKind = Literal["bug_fix", "upgrade", "docs"]


KIND_TITLES: dict[WorkflowKind, str] = {
    "bug_fix": "Reproduce + fix the reported bug",
    "upgrade": "Apply the requested upgrade",
    "docs": "Update the requested documentation",
}

KIND_APPROACHES: dict[WorkflowKind, str] = {
    "bug_fix": (
        "Read the reported issue, reproduce the failure locally, then "
        "make the smallest change that fixes the bug. Add a regression "
        "test that fails before the fix and passes after."
    ),
    "upgrade": (
        "Read the upgrade request, identify the file(s) that pin the "
        "current version, bump to the requested version, and run the "
        "test suite. Update any call-site that broke."
    ),
    "docs": (
        "Read the documentation request and apply the smallest edit "
        "that satisfies it. No code changes; this PR is markdown-only."
    ),
}

KIND_DONE_WHEN: dict[WorkflowKind, str] = {
    "bug_fix": "the failing case from the issue passes and a regression test is added",
    "upgrade": "the upgrade is in place and the test suite is green",
    "docs": "the documentation reads as the issue requested",
}


def render_requirements(*, issue_title: str, issue_body: str, issue_url: str) -> str:
    """Render a synthetic ``requirements.md`` from the issue context."""
    summary = issue_title.strip() or "(no title)"
    body = (issue_body or "(no body provided)").strip()
    return "\n".join(
        [
            f"# Requirements — {summary}",
            "",
            f"> **Source:** {issue_url}",
            "",
            "## Summary",
            "",
            summary,
            "",
            "## Issue body",
            "",
            body,
            "",
            "## Acceptance criteria",
            "",
            (
                "- **AC-001** (R-001) — Given the issue's reproduction, when "
                "the change is applied, then the reported behaviour is resolved."
            ),
            "",
        ],
    )


def render_design(*, kind: WorkflowKind, issue_url: str) -> str:
    """Render a synthetic ``design.md`` describing the kind's approach."""
    return "\n".join(
        [
            f"# Design — {kind} workflow",
            "",
            f"> **Source:** {issue_url}",
            "",
            "## Approach",
            "",
            KIND_APPROACHES[kind],
            "",
            "## Components",
            "",
            "- **issue scope** (`<as referenced in the issue>`) — touched as needed by the fix.",
            "",
            "## Data model",
            "",
            "```text",
            "(no data-model change required by this kind)",
            "```",
            "",
            "## Sequence",
            "",
            "```text",
            "1. read the issue",
            "2. apply the smallest change that resolves it",
            "3. open a PR",
            "```",
            "",
        ],
    )


def render_tasks(*, kind: WorkflowKind, issue_url: str) -> str:
    """Render a synthetic ``tasks.md`` with one task derived from the kind."""
    return "\n".join(
        [
            f"# Tasks — {kind} workflow",
            "",
            f"> **Source:** {issue_url}",
            "",
            "Single-task synthetic spec generated by the Triage dispatcher.",
            "",
            f"- [ ] **T-001** — {KIND_TITLES[kind]}",
            "  - **Implements:** AC-001",
            f"  - **Done when:** {KIND_DONE_WHEN[kind]}",
            "",
        ],
    )
